server:
  port: 8081
spring:
  application:
    name: "course"
  devtools:
    add-properties: false
  servlet:
    multipart:
      enabled: true
      max-file-size: "1000MB"
      max-request-size: "2000MB"
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  datasource:
    url: "${URL_DB:jdbc:postgresql://localhost:5432/course}"
    username: "${USERNAME_DB:postgres}"
    password: "${PASSWORD_DB:root}"
    driverClassName: "org.postgresql.Driver"
  jpa:
    hibernate:
      ddlAuto: "update"
    showSql: "true"
    databasePlatform: "org.hibernate.dialect.PostgreSQLDialect"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapter:
  aws:
    s3:
      bucketName: "${BUCKET_NAME:coursefileslearningacademykatabb}"
      region: "${AWS_REGION:us-east-1}"
      accessKey: "${AWS_ACCESS_KEY}"
      secretKey: "${AWS_SECRET_KEY}"
  restconsumer:
    url: "${AUTH_SERVICE_URL:http://localhost:8080/api/v1/auth}"
resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 100
        slowCallRateThreshold: 100
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "1000s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 100
        slowCallRateThreshold: 100
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "1000s"