-- ==========================================
-- Esquema
-- ==========================================
CREATE SCHEMA IF NOT EXISTS training;
SET search_path TO training;

-- ==========================================
-- Tabla: modules
-- ==========================================
CREATE TABLE IF NOT EXISTS training.modules (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key             VARCHAR(100)  NOT NULL UNIQUE,
    name            VARCHAR(150)  NOT NULL,
    description     TEXT,
    image_url       VARCHAR(300)
);


-- ==========================================
-- Tabla: courses
-- ==========================================
CREATE TABLE IF NOT EXISTS training.courses (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_id    BIGINT NOT NULL,
    title        VARCHAR(255) NOT NULL,
    description  TEXT,
    tags         VARCHAR(255),
    published    BOOLEAN DEFAULT FALSE,
    created_at   TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	coverUrl    VARCHAR(512),
    CONSTRAINT fk_courses_module
        FOREIGN KEY (module_id)
        REFERENCES training.modules (id)
        ON DELETE CASCADE
);

-- ==========================================
-- Tabla: chapters (sin duration_sec)
-- ==========================================
CREATE TABLE IF NOT EXISTS training.chapters (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id     BIGINT NOT NULL,
    title         VARCHAR(255) NOT NULL,
    order_index   INT NOT NULL,
    s3_key        VARCHAR(255),
    content_type  VARCHAR(50),
    CONSTRAINT fk_chapters_course
        FOREIGN KEY (course_id)
        REFERENCES training.courses (id)
        ON DELETE CASCADE,
    CONSTRAINT chk_order_index_positive CHECK (order_index > 0)
);

-- ==========================================
-- Índices adicionales
-- ==========================================
CREATE INDEX IF NOT EXISTS idx_courses_module_id   ON training.courses (module_id);
CREATE INDEX IF NOT EXISTS idx_chapters_course_id  ON training.chapters (course_id);
CREATE INDEX IF NOT EXISTS idx_chapters_order_idx  ON training.chapters (order_index);

-- ==========================================
-- Seeds para modules (idempotentes)
-- ==========================================
INSERT INTO training.modules (key, name, description, image_url) VALUES
    ('FULLSTACK',        'Fullstack',            'Módulo sobre desarrollo Fullstack con frameworks y stacks modernos.', 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800'),
    ('API_INTEGRATIONS', 'APIs e Integraciones', 'Módulo centrado en diseño e implementación de APIs, buses e integraciones.', 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800'),
    ('CLOUD',            'Cloud',                'Módulo enfocado en despliegue y administración en plataformas en la nube.', 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800'),
    ('DATA_ENGINEER',    'Data Engineer',        'Módulo sobre ingeniería de datos y procesamiento de información.', 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800'),
    ('FRONTEND',         'Frontend',             'Módulo sobre desarrollo de interfaces modernas con frameworks como React y TypeScript.', 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800'),
    ('BACKEND',          'Backend',              'Módulo centrado en el desarrollo de servicios y APIs robustas del lado del servidor.', 'https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=800')
ON CONFLICT (key) DO NOTHING;

-- ============================================================
-- SEEDS: COURSES
-- ============================================================
INSERT INTO training.courses (module_id, title, description, tags, published, created_at, coverUrl)
SELECT m.id, c.title, c.description, c.tags, c.published, c.created_at::timestamp, c.coverUrl
FROM (
    VALUES
        -- APIs e Integraciones
        ('APIs e Integraciones', 'Microservicios con API Gateway',
         'Aprende a diseñar y construir arquitecturas de microservicios escalables usando API Gateway.',
         'APIs,Gateway,Best Practices', true, '2025-06-10T12:00:00',
         'https://images.unsplash.com/photo-1518770660439-4636190af475'),

        -- Frontend
        ('Frontend', 'React Avanzado: Hooks y Patterns',
         'Domina los hooks personalizados y patrones avanzados de React para aplicaciones modernas.',
         'React,Hooks,Patterns', true, '2025-07-15T10:00:00',
         'https://images.unsplash.com/photo-1587620962725-abab7fe55159'),

        -- Backend
        ('Backend', 'Node.js y Express: Backend Robusto',
         'Construye APIs robustas y escalables con Node.js y Express.',
         'Node.js,Express,REST', true, '2025-08-01T09:00:00',
         'https://images.unsplash.com/photo-1515879218367-8466d910aaa4'),

        -- Cloud
        ('Cloud', 'AWS: De Zero a Cloud',
         'Aprende a desplegar aplicaciones en AWS desde cero.',
         'AWS,Cloud,DevOps', true, '2025-09-10T11:00:00',
         'https://images.unsplash.com/photo-1515378791036-0648a3ef77b2'),

        -- Data Engineer
        ('Data Engineer', 'Python para Data Engineer',
         'Fundamentos de Python aplicados al análisis y procesamiento de datos.',
         'Python,Data,Analytics', true, '2025-10-05T08:00:00',
         'https://images.unsplash.com/photo-1517430816045-df4b7de11d1d'),

        -- Fullstack
        ('Fullstack', 'Fullstack MERN: Proyecto Completo',
         'Construye aplicaciones fullstack con MongoDB, Express, React y Node.',
         'MERN,Fullstack,MongoDB', true, '2025-09-20T14:00:00',
         'https://images.unsplash.com/photo-1557804506-669a67965ba0'),

        -- Frontend
        ('Frontend', 'TypeScript: Tipado Fuerte',
         'Aprende TypeScript y sus beneficios para proyectos escalables.',
         'TypeScript,JavaScript,Types', true, '2025-08-25T10:00:00',
         'https://images.unsplash.com/photo-1605379399642-870262d3d051'),

        -- Cloud
        ('Cloud', 'Docker: Contenedores en Producción',
         'Domina Docker para desplegar aplicaciones en contenedores.',
         'Docker,Containers,DevOps', true, '2025-07-30T09:30:00',
         'https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc'),

        -- APIs e Integraciones
        ('APIs e Integraciones', 'GraphQL: APIs Modernas',
         'Aprende a construir APIs flexibles con GraphQL.',
         'GraphQL,APIs,Backend', true, '2025-06-20T11:00:00',
         'https://images.unsplash.com/photo-1531482615713-2afd69097998'),

        -- Backend
        ('Backend', 'SQL Avanzado: Optimización',
         'Técnicas avanzadas de SQL para bases de datos relacionales.',
         'SQL,Database,Performance', true, '2025-08-10T13:00:00',
         'https://images.unsplash.com/photo-1519389950473-47ba0277781c')
) AS c(module_name, title, description, tags, published, created_at, coverUrl)
JOIN training.modules m ON m.name = c.module_name
ON CONFLICT DO NOTHING;



-- ============================================================
-- SEEDS: CHAPTERS
-- ============================================================
INSERT INTO training.chapters (course_id, title, order_index, s3_key, content_type)
SELECT crs.id, ch.title, ch.order_index, ch.s3_key, ch.content_type
FROM (
    VALUES
        ('Microservicios con API Gateway', 'Introducción a Microservicios', 1, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4', 'video'),
        ('Microservicios con API Gateway', 'Diseño del Gateway', 2, 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'pdf'),
        ('Microservicios con API Gateway', 'Patrones comunes', 3, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4', 'video'),

        ('React Avanzado: Hooks y Patterns', 'Custom Hooks', 1, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', 'video'),
        ('React Avanzado: Hooks y Patterns', 'Compound Components', 2, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4', 'video'),

        ('Node.js y Express: Backend Robusto', 'Introducción a Express', 1, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4', 'video'),
        ('Node.js y Express: Backend Robusto', 'Middlewares y Autenticación', 2, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4', 'video'),

        ('AWS: De Zero a Cloud', 'Conceptos de Cloud', 1, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4', 'video'),
        ('AWS: De Zero a Cloud', 'EC2 y S3', 2, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4', 'video'),

        ('Python para Data Engineer', 'Python Básico', 1, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4', 'video'),
        ('Python para Data Engineer', 'Pandas y NumPy', 2, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4', 'video'),

        ('Fullstack MERN: Proyecto Completo', 'Setup del Proyecto', 1, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4', 'video'),
        ('Fullstack MERN: Proyecto Completo', 'Backend API', 2, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4', 'video'),
        ('Fullstack MERN: Proyecto Completo', 'Frontend React', 3, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', 'video'),

        ('TypeScript: Tipado Fuerte', 'Tipos Básicos', 1, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4', 'video'),
        ('TypeScript: Tipado Fuerte', 'Interfaces y Generics', 2, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4', 'video'),

        ('Docker: Contenedores en Producción', 'Introducción a Docker', 1, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4', 'video'),
        ('Docker: Contenedores en Producción', 'Docker Compose', 2, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4', 'video'),

        ('GraphQL: APIs Modernas', 'Fundamentos GraphQL', 1, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4', 'video'),
        ('GraphQL: APIs Modernas', 'Resolvers y Mutations', 2, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4', 'video'),

        ('SQL Avanzado: Optimización', 'Índices y Consultas', 1, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4', 'video'),
        ('SQL Avanzado: Optimización', 'Stored Procedures', 2, 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'pdf')
) AS ch(course_title, title, order_index, s3_key, content_type)
JOIN training.courses crs ON crs.title = ch.course_title
ON CONFLICT DO NOTHING;

-- ============================================================
-- USER_CHAPTER_PROGRESS
-- ============================================================
CREATE TABLE training.user_chapter_progress (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    chapter_id BIGINT NOT NULL,
    completed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_chapter_progress_chapter
        FOREIGN KEY (chapter_id) REFERENCES training.chapters (id)
        ON DELETE CASCADE
);

CREATE INDEX idx_user_chapter_progress_user_id
    ON training.user_chapter_progress (user_id);

CREATE INDEX idx_user_chapter_progress_chapter_id
    ON training.user_chapter_progress (chapter_id);

-- ============================================================
-- USER_COURSE_PROGRESS
-- ============================================================
CREATE TABLE training.user_course_progress (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    progress_pct NUMERIC(5,2) DEFAULT 0.00,
    completed_at TIMESTAMP,
    CONSTRAINT fk_user_course_progress_course
        FOREIGN KEY (course_id) REFERENCES training.courses (id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX uq_user_course_progress_user_course
    ON training.user_course_progress (user_id, course_id);

-- ============================================================
-- BADGES
-- ============================================================
CREATE TABLE training.badges (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    icon_s3_key VARCHAR(255),
    criterion VARCHAR(50) NOT NULL DEFAULT 'course_completed',
    course_id BIGINT UNIQUE, -- relación 1:1
    CONSTRAINT fk_badges_course
        FOREIGN KEY (course_id)
        REFERENCES training.courses (id)
        ON DELETE CASCADE
);

-- ============================================================
-- USER_BADGES
-- ============================================================
CREATE TABLE training.user_badges (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    badge_id BIGINT NOT NULL,
    course_id BIGINT,
    awarded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_badges_badge
        FOREIGN KEY (badge_id) REFERENCES training.badges (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_user_badges_course
        FOREIGN KEY (course_id) REFERENCES training.courses (id)
        ON DELETE SET NULL
);

CREATE UNIQUE INDEX uq_user_badges_user_badge_course