-- ==========================================
-- Esquema
-- ==========================================
CREATE SCHEMA IF NOT EXISTS training;
SET search_path TO training;

-- ==========================================
-- Tabla: modules
-- ==========================================
CREATE TABLE IF NOT EXISTS training.modules (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key          VARCHAR(100)  NOT NULL UNIQUE,
    name         VARCHAR(150)  NOT NULL,
    description  TEXT
);

-- ==========================================
-- Tabla: courses
-- ==========================================
CREATE TABLE IF NOT EXISTS training.courses (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_id    BIGINT NOT NULL,
    title        VARCHAR(255) NOT NULL,
    description  TEXT,
    tags         VARCHAR(255),  -- NUEVO: etiquetas separadas por coma o palabra clave
    published    BOOLEAN DEFAULT FALSE,
    created_at   TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_courses_module
        FOREIGN KEY (module_id)
        REFERENCES training.modules (id)
        ON DELETE CASCADE
);

-- ==========================================
-- Tabla: chapters (sin duration_sec)
-- ==========================================
CREATE TABLE IF NOT EXISTS training.chapters (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id     BIGINT NOT NULL,
    title         VARCHAR(255) NOT NULL,
    order_index   INT NOT NULL,
    s3_key        VARCHAR(255),
    content_type  VARCHAR(50),
    CONSTRAINT fk_chapters_course
        FOREIGN KEY (course_id)
        REFERENCES training.courses (id)
        ON DELETE CASCADE,
    CONSTRAINT chk_order_index_positive CHECK (order_index > 0)
);

-- ==========================================
-- Índices adicionales
-- ==========================================
CREATE INDEX IF NOT EXISTS idx_courses_module_id   ON training.courses (module_id);
CREATE INDEX IF NOT EXISTS idx_chapters_course_id  ON training.chapters (course_id);
CREATE INDEX IF NOT EXISTS idx_chapters_order_idx  ON training.chapters (order_index);

-- ==========================================
-- Seeds para modules (idempotentes)
-- ==========================================
INSERT INTO training.modules (key, name, description) VALUES
    ('FULLSTACK',          'Fullstack',            'Módulo sobre desarrollo Fullstack, cubriendo frontend y backend.'),
    ('API_INTEGRATIONS',   'APIs e Integraciones', 'Módulo centrado en diseño e implementación de APIs, buses e integraciones.'),
    ('CLOUD',              'Cloud',                'Módulo enfocado en tecnologías de computación en la nube.'),
    ('DATA_ENGINEER',      'Data Engineer',        'Módulo sobre ingeniería de datos y procesamiento de información.')
ON CONFLICT (key) DO NOTHING;